# Generated by Django 3.2.7 on 2021-09-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
