# Generated by Django 3.2.7 on 2021-09-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johnapp', '0002_auto_20210922_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Person',
        ),
    ]
